"use client"

import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import { Provider } from 'react-redux'
import { store } from '@/store'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'BlogApp',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  )
}
